bloque2_RDCL: bloque2_RDCL.c
	gcc -Werror -Wall -Wextra -pedantic -Wcast-align -Wcast-qual -Wdisabled-optimization -Wformat=2 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wredundant-decls -Wshadow -Wstrict-overflow=5 -Wundef -Wno-unused -Wno-variadic-macros -Wno-parentheses -fdiagnostics-show-option -std=c11 bloque2_RDCL.c -o bloque2_RDCL.o; ./bloque2_RDCL.o
	
# ‘-Wctor-dtor-privacy’ is valid for C++/ObjC++ but not for C
# ‘-Wnoexcept’ is valid for C++/ObjC++ but not for C
# ‘-Wold-style-cast’ is valid for C++/ObjC++ but not for C
# ‘-Woverloaded-virtual’ is valid for C++/ObjC++ but not for C
# ‘-Wsign-promo’ is valid for C++/ObjC++ but not for C
# ‘-Wstrict-null-sentinel’ is valid for C++/ObjC++ but not for C

bloque2_2_RDCL: bloque2_2_RDCL.c
	gcc -Werror -Wall -Wextra -pedantic -Wcast-align -Wcast-qual -Wdisabled-optimization -Wformat=2 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wredundant-decls -Wshadow -Wstrict-overflow=5 -Wundef -Wno-unused -Wno-variadic-macros -Wno-parentheses -fdiagnostics-show-option -std=c11 bloque2_2_RDCL.c -o bloque2_2_RDCL.o; ./bloque2_2_RDCL.o

bloque2_3_RDCL: bloque2_3_RDCL.c
	gcc -Werror -Wall -Wextra -pedantic -Wcast-align -Wcast-qual -Wdisabled-optimization -Wformat=2 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wredundant-decls -Wshadow -Wstrict-overflow=5 -Wundef -Wno-unused -Wno-variadic-macros -Wno-parentheses -fdiagnostics-show-option -std=c11 bloque2_3_RDCL.c -o bloque2_3_RDCL.o; ./bloque2_3_RDCL.o