bloque1_DCL: bloque1_DCL.c
	gcc -Wall -pedantic -std=c11 bloque1_DCL.c -o bloque1_DCL.o; ./bloque1_DCL.o

#There is no main in this exercise
bloque2_DCL: bloque1_2_DCL.c
	gcc -Wall -pedantic -std=c11 bloque1_2_DCL.c -o bloque2_DCL.o; ./bloque2_DCL.o

bloque3_DCL: bloque1_3_main.c
	gcc -Wall -pedantic -std=c11 bloque1_3_main.c -o bloque3_DCL.o; ./bloque3_DCL.o